name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
variables:
  scratch_org_alias: ProvarDX
  connection_name: Admin
  provar_major_version: latest
  test_plan: Regression Plan
steps:
  # Download secure file
  # Download a secure file to the agent machine
  - task: DownloadSecureFile@1
    name: serverKey # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: "server.key"

  - task: DownloadSecureFile@1
    name: licenseFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: "Floating.properties"

  - task: NodeTool@0
    inputs:
      versionSource: spec
      versionSpec: '20.x'
      checkLatest: true
    displayName: "Install Node.js"
    
  - script: |
      npm install -g @salesforce/cli
    displayName: "Node Install: sf cli"

  - script: |
      echo y | sf plugins:install @provartesting/provardx-cli
      sf plugins:update
    displayName: "Install ProvarDX Plugin via SFDX"

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: "Configure JDK 11"
    
  - bash: |
      echo "Set IP of Azure Agent to Variable"
      echo "##vso[task.setvariable variable=AGENT_IP;]`curl ifconfig.me`"
    displayName: "Create variable for Azure Agent IP"

  - task: ShellScript@2
    inputs:
      scriptPath: replace_ip_in_scratch_org_def.sh
      args: $(AGENT_IP) $(Build.SourcesDirectory)/project-scratch-def.json
    displayName: "Insert Whitelist IP in Property File"

  - bash: |
      echo "Download Provar Libraries"
      sf provar automation setup -v $(provar_major_version)
    displayName: "Download & Install Provar Automation CLI"

  - bash: |
      echo "Set ProvarDX Properties in JSON"
      echo "-------------------------------"
      echo "Generating ProvarDX property file"
      echo "-------------------------------"
      sf provar automation config generate -p provardx-properties-generated.json --json
      sf provar automation config load -p provardx-properties-generated.json --json
      echo "\nSetting Provar Home"
      echo "-------------------------------"
      sf provar automation config set provarHome=/ProvarHome
      cat provardx-properties-generated.json
      echo "\nSetting Project Path"
      echo "-------------------------------"
      sf provar automation config set projectPath=/ProvarProject
      cat provardx-properties-generated.json
      echo "\nSetting Results Path"
      echo "-------------------------------"
      sf provar automation config set resultsPath=/ProvarProject/ANT/Results
      cat provardx-properties-generated.json
      echo "\nSetting Test Environment"
      echo "-------------------------------"
      sf provar automation config set environment.testEnvironment=''
      cat provardx-properties-generated.json
      echo "\nSetting Test Plan"
      echo "-------------------------------"
      sf provar automation config set testPlan='["Regression Plan"]'    
      cat provardx-properties-generated.json
      echo "\nSetting Test Plan Features"
      echo "-------------------------------"
      sf provar automation config set testplanFeatures='[{"name": "PDF", "type": "OUTPUT", "enabled": "true"}, {"name": "PIECHART", "type": "OUTPUT", "enabled": "true"}, {"name": "EMAIL", "type": "NOTIFICATION", "enabled": "false"}, {"name": "TEST_MANAGER", "type": "REPORTING", "enabled": "true"}]'                
      cat provardx-properties-generated.json
      echo "\nSetting Test Project Secrets"
      echo "-------------------------------"
      sf provar automation config set testprojectSecrets="$(secrets_password)"
    displayName: "Generate & Configure ProvarDX Property File"

  - bash: |
      echo "Download Provar Libraries"
      sf provar automation setup -v $(provar_major_version)
    displayName: "Download & Install Provar Automation CLI"

  - bash: |
      mkdir -p $HOME/Provar/.licenses
      cp $(licenseFile.secureFilePath) $HOME/Provar/.licenses
    displayName: "Set License path for Provar CLI"
      
  - bash: |
      echo "Creating SFDX Project"
      sf project generate -n SFDXProject
      ls -la SFDXProject
      cp project-scratch-def.json SFDXProject/config/.
      cp .forceignore SFDXProject/.
    displayName: "Creates SFDX Project with some sample configuration files"

  - bash: | 
      sf auth jwt grant --client-id $(consumer_key) --jwt-key-file "$(serverKey.secureFilePath)" --username $(dev_hub_username) --set-default-dev-hub --alias $(dev_hub_alias)
    displayName: "Authenticates to Dev Hub Org"

  - bash: |
      sf org list --clean
    displayName: "Cleans stale Org authentications"

  - bash: |
      sf org create scratch -f SFDXProject/config/project-scratch-def.json --alias $(scratch_org_alias)
      sf org display --target-org $(scratch_org_alias)
    displayName: "Create Scratch Org and Org description"

  - task: ShellScript@2
    inputs:
      scriptPath: setup_dreamhouse.sh
      args: $(scratch_org_alias)
    displayName: "Deploy and Setup Dreamhouse App"

  - bash: |
      sf provar automation validate --json
    displayName: "Validate ProvarDX property file"

  - bash: |
      sf provar automation compile --json
    displayName: "Compile Provar Tests"

  - bash: |
      sf provar automation metadata download --connections Admin --json
    displayName: "Download Salesforce Metadata"

  - bash: |
      xvfb sf provar automation test run --json
    displayName: "Run Provar Tests"

  - bash: |
      sf org delete scratch --target-org $(scratch_org_alias) --no-prompt
    displayName: "Delete Scratch Org"
    
  # Publish Test Results
  - task: PublishTestResults@2
    continueOnError: true
    inputs:
      testResultsFormat: "JUnit" # Options: JUnit, NUnit, VSTest, xUnit, cTest
      testResultsFiles: "**/Results/*.xml"
      #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
      #mergeTestResults: false # Optional
      failTaskOnFailedTests: true # Optional
      testRunTitle: ProvarDX Test Suite # Optional
    displayName: "Publish JUnit Test Results"

  # Publish (upload) a file or directory as a named artifact for the current run
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/ProvarProject/ANT/Results'
      artifact: 'Test Results'
      publishLocation: 'pipeline'
    displayName: "Publish Test Results Zip"
