# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

variables:
  TEST_PLAN: "Regression Plan"
  ENVIRONMENT: ""
  
jobs:
- job: Windows
  pool: 
    name: Local
    demands: 
    - InteractiveSession -equals True
  steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script - Run Provar Tests'
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.          
          ant -f $(Build.SourcesDirectory)/ProvarProject/ANT/build_azure.xml -v -DprovarSecretsPassword=$(secrets_password)
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/ANT/Results/*.xml'
      inputs:
        testResultsFiles: '**/ANT/Results/*.xml'
        testRunTitle: 'Windows-$(TEST_PLAN) Report'
      condition: succeededOrFailed()  