# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm install -g sfdx-cli
    npm install -g yarn
    npm install openssl-nodejs
  displayName: 'npm install sfdx-cli, yarn, and openssl'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd com.provar.plugins.provardx
      sfdx plugins:link
  displayName: 'Link ProvarDX SFDX plugins with SFDX'
- bash: |
    cd com.provar.plugins.provardx
    yarn run prepack
  displayName: 'Execute yarn command prepack available in package.json file'
- bash: |
    sfdx force:project:create -n ProvarDX
    cp project-scratch-def.json ProvarDX/config/project-scratch-def.json
  displayName: 'Creates SFDX Project with some sample configuration files'
- bash: |
    openssl aes-256-cbc -k $(key_password) -md md5 -in assets/server.key.enc -out assets/server.key -d
    sfdx force:auth:jwt:grant --clientid $(consumer_key) --jwtkeyfile assets/server.key --username provartrial57@gmail.com --setdefaultdevhubusername --setalias $(dev_hub_alias)
  displayName: 'Authenticates to Dev Hub Org'
- bash: |
    sfdx force:org:create -f ProvarDX/config/project-scratch-def.json
    sfdx force:org:display -u $(dev_hub_username)
  displayName: 'Create Scratch Org and give description for the Org'
- bash: |
    sfdx force:user:password:generate --targetusername $(dev_hub_username)
  displayName: 'Generate a password for Scratch Org for given user'
- bash: |
    echo "Install Provar"
    wget -nv https://download.provartesting.com/latest/Provar_ANT_latest.zip
    unzip -q Provar_ANT_latest.zip -d /home/vsts/work/1/s/ProvarHome
  displayName: 'Install Provar'
- bash: |
    cd com.provar.plugins.provardx
    sfdx provar:validate
  displayName: 'Validate ProvarDX property file'
- bash: |
    cd com.provar.plugins.provardx 
    sfdx provar:runtests
  displayName: 'Run Provar Tests'

  
