name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - docker

jobs:
- job: Build
  displayName: "Build ProvarDX Docker Image"
  pool:
    vmImage: "ubuntu-latest"
  variables:
    provar_major_version: latest
    provar_default_version: latest
  steps:
    # Download secure file
    # Download a secure file to the agent machine
    - task: DownloadSecureFile@1
      name: serverKey # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
      inputs:
        secureFile: "server.key"

    - script: |
        cp $(serverKey.secureFilePath) $(System.DefaultWorkingDirectory)
        ls -la $(System.DefaultWorkingDirectory)
      displayName: "Copy server key to Docker build context (base working dir)"

    - task: Docker@2
      inputs:
        command: build
        containerRegistry: 'Provar Testing Docker Hub'
        repository: 'provartesting/provar'
        tags: provardx
        arguments: --label buildtype=azure 
          --build-arg PROVAR_DEFAULT_VERISON=$(provar_default_version) 
          --build-arg PROVAR_MAJOR_VERSION=$(provar_major_version) 
      displayName: "Build ProvarDX Docker image"

    - task: Docker@2
      inputs:
        containerRegistry: 'Provar Testing Docker Hub'
        repository: 'provartesting/provar'
        command: push
        tags: provardx
      displayName: "Push Docker image to registry"

- job: Linux
  dependsOn: Build
  variables:     
    scratch_org_username: $(Build.BuildNumber)@provartesting.com
    connection_name: Admin
    instance_url: https://login.salesforce.com
    test_environment: ProvarDX
    provardx_property_file: provardx-properties-docker.json
  pool: 
    vmImage: 'ubuntu-latest'
  container: 
    image: provartesting/provar:provardx
    endpoint: 'Provar Testing Docker Hub'
    volumes:
      - /home/vsts/work/1/s/:/home/ProvarProject/ANT/Results
    options: --env CONSUMER_KEY=$(consumer_key) 
          --env SCRATCH_ORG_USERNAME=$(scratch_org_username) 
          --env DEV_HUB_USERNAME=$(dev_hub_username) 
          --env DEV_HUB_ALIAS=$(dev_hub_alias) 
          --env SCRATCH_ORG_ALIAS=$(scratch_org_alias) 
          --env ProvarSecretsPassword=$(secrets_password) 
          --env ENV=$(test_environment) 
          --env INSTANCE_URL=$(instance_url) 
          --env PROVARDX_PROPERTY_FILE=$(provardx_property_file)

  steps:
  - script: |
      /home/create_scratch_org.sh
    displayName: "Create Scratch Org and Deploy Metadata"
  - script: |
      /home/run_provar_tests.sh
    displayName: "Run Provar Tests in Docker Container"
  - script: |
      /home/delete_scratch_org.sh
    displayName: "Delete Scratch Org"

  # Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit" # Options: JUnit, NUnit, VSTest, xUnit, cTest
      testResultsFiles: "**/JUnit.xml"
      searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
      #mergeTestResults: false # Optional
      failTaskOnFailedTests: true # Optional
      testRunTitle: ProvarDX Test Suite # Optional
    displayName: "Publish JUnit Test Results"