name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - google-poc

pool:
  vmImage: "ubuntu-latest"
variables:
  provar_major_version: latest
  provar_build_version: latest
steps:

  - bash: |
      echo "Download Provar Libraries"
      wget -nv https://download.provartesting.com/$(provar_major_version)/Provar_ANT_$(provar_build_version).zip
      echo "Unzip Provar ANT Files"
      unzip -q Provar_ANT_$(provar_build_version).zip -d $BUILD_SOURCESDIRECTORY/ProvarHome
      export PROVAR_HOME=$BUILD_SOURCESDIRECTORY/ProvarHome
      cp -r $BUILD_SOURCESDIRECTORY/ProvarProject/provardx $PROVAR_HOME/provardx
      ## cp -r $BUILD_SOURCESDIRECTORY/ProvarProject/.licenses $PROVAR_HOME/.licenses
      cd $PROVAR_HOME
      ls -la
    displayName: "Install & Configure Provar"

  - task: Ant@1
    inputs:
      buildFile: 'build.xml'
      options: '-DsecretsPassword=$(google_secrets_password)'
      publishJUnitResults: true
      testResultsFiles: '**/Results/*.xml'
      testRunTitle: 'Google POC Test Run'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'

  # Publish (upload) a file or directory as a named artifact for the current run
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/ProvarProject/ANT/Results'
      artifact: 'Test Results'
      publishLocation: 'pipeline'
    displayName: "Publish Test Results Zip"
