version: 2.1
orbs:
    provar: provartesting/provar@2.3.1
jobs:
    build:
        executor:
            name: provar/default
            tag: 8-jdk-stretch-node-browsers
        parameters:
            build_file:
                default: build_circleci.xml
                type: string
            project_name:
                default: ProvarProject
                type: string
            test_plan:
                default: "Regression Plan"
                type: string
            environment:
                default: ""
                type: string
            email_target:
                default: michael.dailey@provartesting.com
                type: string
        # working_directory: ~/ProvarProject 
        steps:
        - checkout
        - provar/setup_provar
        # - run:
        #     command: ls -laR
        #     name: "Outputting directory contents for debugging"
        - run: 
            command: ant -Dprovar.home="/home/circleci/project/Provar_Home" -Dtest.plan=<< parameters.test_plan >> -Denvironment=<< parameters.environment >> -Demail.target=<< parameters.email_target >> -f << parameters.project_name >>/ANT/<< parameters.build_file >>
            name: "Run Provar Tests"
        # Store Test Results (JUnit and zipped report)
        - store_test_results:
            path: "~/ProvarProject/ANT/Results*"
