version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1
  provar: provartesting/provar@2.18.0
jobs:
  name: "Run Provar Tests"
  build:     
    executor:
      name: provar/default
      tag: current-browsers
    parameters:
      build_file:
        default: build_circleci.xml
        type: string
      environment:
        default: ""
        type: string
      project_name:
        default: ProvarProject
        type: string
      test_plan:
        default: Regression Plan
        type: string
      license_path:
        default: /home/circleci/project/ProvarProject/.licenses
        type: string
      email_target:
        default: michael.dailey@provartesting.com
        type: string
    steps:
      - checkout
      - provar/setup_provar:
          majorversion: 2.14.1
          url: download.provartesting.com
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: sudo apt-get update -y && sudo apt-get install -y ant
      - run:
          command: |
            mkdir /home/circleci/project/ProvarProject/.licenses
            cp -r /home/circleci/project/.licenses /home/circleci/project/ProvarProject/.licenses

      - provar/run_test_plans:
          build_file: << parameters.build_file >>
          email_target: << parameters.email_target >>
          environment: << parameters.environment >>
          project_name: << parameters.project_name >>
          test_plan: << parameters.test_plan >>
          license_path: << parameters.license_path >>
      - provar/store_provar_test_results:
          project_name: << parameters.project_name >>