version: 2.1
orbs:
    provar: provartesting/provar@2.6.3
jobs:
    build:
        executor:
            name: provar/default
            tag: 8-jdk-stretch-node-browsers
        parameters:
            # Name of the build file to execute
            build_file:
                default: build_circleci.xml
                type: string
            # This is just for extra parameterization and shouldn't be changed unless you need to
            project_name:
                default: ProvarProject
                type: string
            # The name of your test plan to execute
            test_plan:
                default: "Regression Plan"
                type: string
            # Used to define the Provar Test Environment for Environment Overrides
            environment:
                default: ""
                type: string
            # Email address to send test results/reports to
            email_target:
                default: michael.dailey@provartesting.com
                type: string
            test_folder:
                default: Regression
                type: string
        steps:
        - checkout
        - provar/setup_provar
        - run: 
            command: ant -Dprovar.home="/home/circleci/project/Provar_Home" -Dproject.home="/home/circleci/project/<< parameters.project_name >>" 
                -Dtest.plan="<< parameters.test_plan >>" -Denvironment="<< parameters.environment >>" 
                -Demail.target=<< parameters.email_target >> -Dtest.folder="<< parameters.test_folder >>" -f << parameters.project_name >>/ANT/<< parameters.build_file >>
            name: "Run Provar Tests"
        # Store Test Results (JUnit and zipped report)
        - store_test_results:
            path: "ProvarProject/ANT/Results/JUnit html/"
        
        - store_artifacts:
            path: ProvarProject/ANT/Results