version: 2.1
orbs:
    provar: provartesting/provar@2.13
workflows:
    version: 2.1
    run_all:
        jobs:
            - provar/run_provar:
                majorversion: 2.11.2
                minorversion: '05'
                url: download.provartesting.com
                project_name: ProvarProject
                build_file: build_circleci.xml
                test_plan:  "Regression Plan"
                environment: ""
                email_target: michael.dailey@provartesting.com
                name: "Execute Provar Tests"
