steps:
  - command: 
    - "echo \" pwd: \" pwd "
  - label: "Insert Secrets Password"
    command:
    - "echo $$BUILDKITE_BUILD_CHECKOUT_PATH"
    - "insert_secrets_password.sh ProvarDevOps2021 $$BUILDKITE_BUILD_CHECKOUT_PATH/provardx-properties-buildkite.json"
    - "cat $$BUILDKITE_BUILD_CHECKOUT_PATH/provardx-properties-buildkite.json"
  - label: "Run Regression Tests"    
    command:
    - "sfdx provar:runtests -p provardx-properties-buildkite.json"
    plugins:
      - test-collector#v1.0.0:
          files: "ANT/Results/JUnit.xml"
          format: "junit"
    artifact_paths: "**/JUnit.xml"