steps:
  - label: "Insert Secrets Password"
    command:
    - "sh insert_secrets_password.sh ProvarDevOps2021 ${BUILDKITE_BUILD_CHECKOUT_PATH}/provardx-properties-buildkite.json"
    - "cat ${BUILDKITE_BUILD_CHECKOUT_PATH}/provardx-properties-buildkite.json"
    - "sfdx provar:runtests -p ${BUILDKITE_BUILD_CHECKOUT_PATH}/provardx-properties-buildkite.json"
    key: "tests"
    plugins:
    - test-collector#v1.0.0:
        files: "ANT/Results/JUnit.xml"
        format: "junit"
    artifact_paths: "**/JUnit.xml"